import Head from 'next/head'
import React from 'react'

const AutoLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <Head>
        <title>denpa-tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { children }
      </main>
    </div>
  )
}

export {AutoLayout}